spring.application.name=oauth-server

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jwt.secret=ThisIsMyVeryLongSuperSecretKeyForJwtSigning1234567890
jwt.access-expiration=3600000
jwt.refresh-expiration=604800000